const faces = [
     {
          face0: "a01.PNG",
          face1: "b01.PNG",
          face2: "c01.PNG",
          different: 2
     }, {
          face0: "a02.PNG",
          face1: "b02.PNG",
          face2: "c02.PNG",
          different: 1
     }, {
          face0: "a03.PNG",
          face1: "b03.PNG",
          face2: "c03.PNG",
          different: 1
     }, {
          face0: "a04.PNG",
          face1: "b04.PNG",
          face2: "c04.PNG",
          different: 1
     }, {
          face0: "a05.PNG",
          face1: "b05.PNG",
          face2: "c05.PNG",
          different: 2
     }, {
          face0: "a06.PNG",
          face1: "b06.PNG",
          face2: "c06.PNG",
          different: 2
     }, {
          face0: "a07.PNG",
          face1: "b07.PNG",
          face2: "c07.PNG",
          different: 1
     }, {
          face0: "a08.PNG",
          face1: "b08.PNG",
          face2: "c08.PNG",
          different: 2
     }, {
          face0: "a09.PNG",
          face1: "b09.PNG",
          face2: "c09.PNG",
          different: 0
     }, {
          face0: "a10.PNG",
          face1: "b10.PNG",
          face2: "c10.PNG",
          different: 2
     }, {
          face0: "a11.PNG",
          face1: "b11.PNG",
          face2: "c11.PNG",
          different: 0
     }, {
          face0: "a12.PNG",
          face1: "b12.PNG",
          face2: "c12.PNG",
          different: 2
     }, {
          face0: "a13.PNG",
          face1: "b13.PNG",
          face2: "c13.PNG",
          different: 1
     }, {
          face0: "a14.PNG",
          face1: "b14.PNG",
          face2: "c14.PNG",
          different: 0
     }, {
          face0: "a15.PNG",
          face1: "b15.PNG",
          face2: "c15.PNG",
          different: 1
     }, {
          face0: "a16.PNG",
          face1: "b16.PNG",
          face2: "c16.PNG",
          different: 1
     }, {
          face0: "a17.PNG",
          face1: "b17.PNG",
          face2: "c17.PNG",
          different: 1
     }, {
          face0: "a18.PNG",
          face1: "b18.PNG",
          face2: "c18.PNG",
          different: 1
     }, {
          face0: "a19.PNG",
          face1: "b19.PNG",
          face2: "c19.PNG",
          different: 2
     }, {
          face0: "a20.PNG",
          face1: "b20.PNG",
          face2: "c20.PNG",
          different: 0
     }, {
          face0: "a21.PNG",
          face1: "b21.PNG",
          face2: "c21.PNG",
          different: 1
     }, {
          face0: "a22.PNG",
          face1: "b22.PNG",
          face2: "c22.PNG",
          different: 1
     }, {
          face0: "a23.PNG",
          face1: "b23.PNG",
          face2: "c23.PNG",
          different: 0
     }, {
          face0: "a24.PNG",
          face1: "b24.PNG",
          face2: "c24.PNG",
          different: 0
     }, {
          face0: "a25.PNG",
          face1: "b25.PNG",
          face2: "c25.PNG",
          different: 0
     }, {
          face0: "a26.PNG",
          face1: "b26.PNG",
          face2: "c26.PNG",
          different: 0
     }, {
          face0: "a27.PNG",
          face1: "b27.PNG",
          face2: "c27.PNG",
          different: 0
     }, {
          face0: "a28.PNG",
          face1: "b28.PNG",
          face2: "c28.PNG",
          different: 2
     }, {
          face0: "a29.PNG",
          face1: "b29.PNG",
          face2: "c29.PNG",
          different: 0
     }, {
          face0: "a30.PNG",
          face1: "b30.PNG",
          face2: "c30.PNG",
          different: 2
     }, {
          face0: "a31.PNG",
          face1: "b31.PNG",
          face2: "c31.PNG",
          different: 1
     }, {
          face0: "a32.PNG",
          face1: "b32.PNG",
          face2: "c32.PNG",
          different: 1
     }, {
          face0: "a33.PNG",
          face1: "b33.PNG",
          face2: "c33.PNG",
          different: 0
     }, {
          face0: "a34.PNG",
          face1: "b34.PNG",
          face2: "c34.PNG",
          different: 0
     }, {
          face0: "a35.PNG",
          face1: "b35.PNG",
          face2: "c35.PNG",
          different: 1
     }, {
          face0: "a36.PNG",
          face1: "b36.PNG",
          face2: "c36.PNG",
          different: 2
     }, {
          face0: "a37.PNG",
          face1: "b37.PNG",
          face2: "c37.PNG",
          different: 0
     }, {
          face0: "a38.PNG",
          face1: "b38.PNG",
          face2: "c38.PNG",
          different: 0
     }, {
          face0: "a39.PNG",
          face1: "b39.PNG",
          face2: "c39.PNG",
          different: 1
     }, {
          face0: "a40.PNG",
          face1: "b40.PNG",
          face2: "c40.PNG",
          different: 2
     }, {
          face0: "a41.PNG",
          face1: "b41.PNG",
          face2: "c41.PNG",
          different: 1
     }, {
          face0: "a42.PNG",
          face1: "b42.PNG",
          face2: "c42.PNG",
          different: 1
     }, {
          face0: "a43.PNG",
          face1: "b43.PNG",
          face2: "c43.PNG",
          different: 2
     }, {
          face0: "a44.PNG",
          face1: "b44.PNG",
          face2: "c44.PNG",
          different: 2
     }, {
          face0: "a45.PNG",
          face1: "b45.PNG",
          face2: "c45.PNG",
          different: 2
     }, {
          face0: "a46.PNG",
          face1: "b46.PNG",
          face2: "c46.PNG",
          different: 1
     }, {
          face0: "a47.PNG",
          face1: "b47.PNG",
          face2: "c47.PNG",
          different: 1
     }, {
          face0: "a48.PNG",
          face1: "b48.PNG",
          face2: "c48.PNG",
          different: 0
     }, {
          face0: "a49.PNG",
          face1: "b49.PNG",
          face2: "c49.PNG",
          different: 0
     }, {
          face0: "a50.PNG",
          face1: "b50.PNG",
          face2: "c50.PNG",
          different: 0
     }, {
          face0: "a51.PNG",
          face1: "b51.PNG",
          face2: "c51.PNG",
          different: 0
     }, {
          face0: "a52.PNG",
          face1: "b52.PNG",
          face2: "c52.PNG",
          different: 1
     }, {
          face0: "a53.PNG",
          face1: "b53.PNG",
          face2: "c53.PNG",
          different: 1
     }, {
          face0: "a54.PNG",
          face1: "b54.PNG",
          face2: "c54.PNG",
          different: 2
     }, {
          face0: "a55.PNG",
          face1: "b55.PNG",
          face2: "c55.PNG",
          different: 1
     }, {
          face0: "a56.PNG",
          face1: "b56.PNG",
          face2: "c56.PNG",
          different: 2
     }, {
          face0: "a57.PNG",
          face1: "b57.PNG",
          face2: "c57.PNG",
          different: 2
     }, {
          face0: "a58.PNG",
          face1: "b58.PNG",
          face2: "c58.PNG",
          different: 0
     }, {
          face0: "a59.PNG",
          face1: "b59.PNG",
          face2: "c59.PNG",
          different: 1
     }, {
          face0: "a60.PNG",
          face1: "b60.PNG",
          face2: "c60.PNG",
          different: 0
     }
]

export default faces;